### PR TITLE
Fix undefined behavior in `Generator::update`

### LINKED ISSUE #35: Undefined Behavior in Generator::update
This is an awesome tool, thanks for making this available for studying! One minor implementation thing:

In `Generator::update` you have:

```rust
// A little cheat to avoid taking excessive locks.
//
// Access to `coord_map` and `color_map` is governed by values in `self.resolved`,
// in such a way that any values in the former will not be accessed until the latter is updated.
// Since `coord_map` and `color_map` also contain 'plain old data', we can set them directly
// by getting the raw pointers. The subsequent access to `self.resolved` goes through a lock,
// and ensures correct memory ordering.
#[allow(clippy::cast_ref_to_mut)]
unsafe {
    *(self.coord_map.as_ptr() as *mut (Coord2D, MapId)).add(flat_coord.0 as usize) =
        (example_coord, example_map_id);

    *(self.id_map.as_ptr() as *mut (PatchId, MapId)).add(flat_coord.0 as usize) = island_id;

    *(self.color_map.get_pixel(update_coord.x, update_coord.y) as *const image::Rgba<u8>
        as *mut image::Rgba<u8>) = *example_maps[example_map_id.0 as usize]
        .get_pixel(example_coord.x, example_coord.y);
}
```

Unfortunately, I believe, this is undefined behavior. The documentation for `Vec::as_ptr` states

> "The caller must also ensure that the memory the pointer (non-transitively) points to is never written to (except inside an UnsafeCell) using this pointer or any pointer derived from it."

The problem with UB (here) is not the order of access governance during runtime; but a property of the code during compile time; as a "contract" between the programmer and the compiler are formed regarding what is possible with that pointer.

Although today this might work just fine, any future compiler version (or code change, or different LLVM target backend) could _invoke_ this contract, and exploit the guarantee that e.g., `coord_map`'s backing heap storage "could not" have been changed via the `as_ptr()` pointer.

When that happens, the program might be 'optimized' in arbitrary ways, basically _anything_ goes.

### Possible Solutions

Just some random brainstorming:

- Put content of the maps into `UnsafeCells` (might look a bit ugly)
- Add locks like for other fields (overhead)
- Take `&self` as `&mut self` (probably interferes with the `crossbeam_utils::thread::scope` closure and needs more rearchitecting)

### Misc

Bonus quote from rkruppe since I was unsure about `as_ptr` myself:

> [...] The precise rules for when mutation is allowed and through what pointers are still undecided, but the current best proposals (Ralf Jung's stacked borrows in its various iterations) are not primarily about what references are "floating around" somewhere but about permission to read/write for each part of memory (each of which applies to a subset of pointers and the permissions change as references and pointers get created and used). The code in as_ptr never creates any permission to mutate the Vec's buffer, so writing to it is UB [...]

### PR DESCRIPTION
**Pull request by h3r2tic**
Background info in #35.

This opts to keep the unsafe mutation of the two `Vec<T>`ors and one `RgbaImage`, but wraps those in semi-safe wrappers, only allowing limited mutation, and using `UnsafeCell` under the hood.

Fixes #35

### CODE REVIEW

**Comment by repi** [comment]
Sweet.

Also don't forget to add an ittem in the unreleased section of the changelog (can link the PR there also).

File: lib/src/unsync.rs [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+
+pub struct UnsyncVec<T: Copy>(UnsafeCell<Vec<T>>);
+pub struct UnsyncRgbaImage(UnsafeCell<image::RgbaImage>);
+
+impl<T: Copy> UnsyncVec<T> {
+    pub fn new(v: Vec<T>) -> Self {
+        Self(UnsafeCell::new(v))
+    }
+
+    pub fn assign_at(&self, idx: usize, value: T) {
```
Comment (MaikKlein) [inline lib/src/unsync.rs]: This should be unsafe.

File: lib/src/unsync.rs [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+
+    pub fn as_ref(&self) -> &image::RgbaImage {
+        unsafe { self.0.get().as_ref() }.unwrap()
+    }
+
+    pub fn into_inner(self) -> image::RgbaImage {
+        self.0.into_inner()
+    }
+
+    pub fn put_pixel(&self, x: u32, y: u32, pixel: image::Rgba<u8>) {
```
Comment (MaikKlein) [inline lib/src/unsync.rs]: This also should be unsafe.

Comment (h3r2tic) [reply lib/src/unsync.rs]: This one is safe!

File: lib/src/unsync.rs (hunk 1 above)
Comment (h3r2tic) [reply lib/src/unsync.rs]: Okays!
